version: '3.9'
services:
  accounts:
    image: ca-bh/account:latest
    ports:
      - 8080:8080
    restart: on-failure
  transactions:
    image: ca-bh/transaction:latest
    ports:
      - 8081:8081
    restart: on-failure
  balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5000:5000
    depends_on:
      - transactions
      - accounts
    restart: on-failure
